// <auto-generated />
namespace TravelWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PhanQuyen1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PhanQuyen1));
        
        string IMigrationMetadata.Id
        {
            get { return "201711031027103_PhanQuyen1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
